default: &default
  adapter: postgresql
  host: dpg-cfjq35ta49903fkvqa20-a.frankfurt-postgres.render.com
  username: jobtracker_user
  password: VEajL1Qfkx157ufoOlh50LFtzC12adeE
  encoding: unicode

development:
  <<: *default
  database: jobtracker

test:
  <<: *default
  database: jobtracker
  port: 5432

production:
  <<: *default
  database: jobtracker
  username: jobtracker_user
  password: VEajL1Qfkx157ufoOlh50LFtzC12adeE
  host: dpg-cfjq35ta49903fkvqa20-a.frankfurt-postgres.render.com
  port: 5432
